
services:
  flight-database:
    container_name: flight-database
    image: postgres:17-alpine
    env_file:
      - dev.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flight-network

  flight-backend:
    container_name: flight-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - flight-database
    command: uvicorn --reload --host 0.0.0.0 --port 8000 main:app 
    env_file:
      - src/.env
    volumes:
      - ./src:/app:cached
    networks:
      - flight-network
    

volumes:
  postgres_data:

networks:
  flight-network:
    driver: bridge